// <auto-generated />
using System;
using DoktormandenDk.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoktormandenDk.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231021155159_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoktormandenDk.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateTime>("AppointmentTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GPId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppointmentId");

                    b.HasIndex("GPId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentTime = new DateTime(2023, 10, 21, 17, 51, 59, 46, DateTimeKind.Local).AddTicks(2316),
                            GPId = 1,
                            PatientId = 2,
                            Subject = "Hul i hovedet"
                        });
                });

            modelBuilder.Entity("DoktormandenDk.Models.GP", b =>
                {
                    b.Property<int>("GPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GPId"));

                    b.Property<string>("License")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GPId");

                    b.ToTable("GP");

                    b.HasData(
                        new
                        {
                            GPId = 1,
                            License = "AB3532Z",
                            Name = "Børge Ordrup",
                            UserName = "Læge 1"
                        },
                        new
                        {
                            GPId = 2,
                            License = "ZZ9922B",
                            Name = "Klaus Spellenberg",
                            UserName = "Læge 2"
                        });
                });

            modelBuilder.Entity("DoktormandenDk.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            BirthDay = new DateTime(1959, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peter Hansen",
                            UserName = "Patient A"
                        },
                        new
                        {
                            PatientId = 2,
                            BirthDay = new DateTime(1976, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ole Jensen",
                            UserName = "Patient B"
                        });
                });

            modelBuilder.Entity("DoktormandenDk.Models.Appointment", b =>
                {
                    b.HasOne("DoktormandenDk.Models.GP", "GP")
                        .WithMany("Appointments")
                        .HasForeignKey("GPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoktormandenDk.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GP");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DoktormandenDk.Models.GP", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DoktormandenDk.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
